/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val android_gradle_plugin: String = "4.1.3"
    const val kotlin_gradle_plugin: String = "1.4.20"

    const val android_core_ktx: String = "1.5.0-beta01"
    const val android_appcompat: String = "1.2.0"
    const val android_material: String = "1.3.0"
    const val android_constraintlayout: String = "2.0.4"
    const val android_lifecycle_extensions: String = "2.2.0"
    const val android_lifecycle_viewmodel: String = "2.3.0-rc01"
    const val android_lifecycle_livedata: String = "2.3.0-rc01"
    const val android_gson: String = "2.8.6"
    const val android_coroutines: String = "1.4.2"
    const val android_room: String = "2.2.6"

    const val kotlin_stdlib_jdk7: String = "1.4.30"
    const val kotlin_coroutine_core: String = "1.4.2"

    const val koin: String = "3.1.2"

    const val squareup_retrofit2: String = "2.9.0"
    const val squareup_retrofit2_coroutines: String = "0.9.2"
    const val squareup_okhttp3_logging: String = "4.9.1"
}
